# Lecture no 14 (Pandas):-

In [36]:
import pandas as pd

In [37]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [38]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [39]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [40]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [41]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [42]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [43]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [44]:
df[['Name','Sex','Ticket','Cabin','Embarked']]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [45]:
df.dtypes == 'object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [46]:
df.dtypes == 'float64'

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare            True
Cabin          False
Embarked       False
dtype: bool

In [47]:
df[df.dtypes[df.dtypes=='float64'].index]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [48]:
df[df.dtypes[df.dtypes=='int64'].index]

     PassengerId  Survived  Pclass  SibSp  Parch
0              1         0       3      1      0
1              2         1       1      1      0
2              3         1       3      0      0
3              4         1       1      1      0
4              5         0       3      0      0
..           ...       ...     ...    ...    ...
886          887         0       2      0      0
887          888         1       1      0      0
888          889         0       3      1      2
889          890         1       1      0      0
890          891         0       3      0      0

[891 rows x 5 columns]

In [49]:
df[df.dtypes[df.dtypes=='bool64'].index]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[891 rows x 0 columns]

In [50]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [51]:
df.head(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C

In [52]:
df.tail(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [53]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [54]:
df[['Ticket']]

               Ticket
0           A/5 21171
1            PC 17599
2    STON/O2. 3101282
3              113803
4              373450
..                ...
886            211536
887            112053
888        W./C. 6607
889            111369
890            370376

[891 rows x 1 columns]

In [55]:
df[['Ticket']][4:16]

       Ticket
4      373450
5      330877
6       17463
7      349909
8      347742
9      237736
10    PP 9549
11     113783
12  A/5. 2151
13     347082
14     350406
15     248706

In [56]:
df[['Ticket']][4:16:2]

       Ticket
4      373450
6       17463
8      347742
10    PP 9549
12  A/5. 2151
14     350406

In [57]:
df[['Ticket','Cabin']]

               Ticket Cabin
0           A/5 21171   NaN
1            PC 17599   C85
2    STON/O2. 3101282   NaN
3              113803  C123
4              373450   NaN
..                ...   ...
886            211536   NaN
887            112053   B42
888        W./C. 6607   NaN
889            111369  C148
890            370376   NaN

[891 rows x 2 columns]

In [58]:
df[['Ticket','Cabin']][4:17]

       Ticket Cabin
4      373450   NaN
5      330877   NaN
6       17463   E46
7      349909   NaN
8      347742   NaN
9      237736   NaN
10    PP 9549    G6
11     113783  C103
12  A/5. 2151   NaN
13     347082   NaN
14     350406   NaN
15     248706   NaN
16     382652   NaN

In [59]:
df[['Ticket','Cabin']][4:17:3]

     Ticket Cabin
4    373450   NaN
7    349909   NaN
10  PP 9549    G6
13   347082   NaN
16   382652   NaN

In [60]:
df[['Ticket','Cabin','Name']][4:17:3]

     Ticket Cabin                             Name
4    373450   NaN         Allen, Mr. William Henry
7    349909   NaN   Palsson, Master. Gosta Leonard
10  PP 9549    G6  Sandstrom, Miss. Marguerite Rut
13   347082   NaN      Andersson, Mr. Anders Johan
16   382652   NaN             Rice, Master. Eugene

In [61]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [62]:
df['new_col'] = 7

In [63]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,7
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,7
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,7
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,7
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,7
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,7
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,7

In [64]:
df.insert(loc=3, column='Food',value=0)

In [65]:
df

,PassengerId,Survived,Pclass,Food,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,7
2,3,1,3,0,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
3,4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,7
4,5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,7
887,888,1,1,0,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,7
888,889,0,3,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,7
889,890,1,1,0,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,7
890,891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,7

In [66]:
df.insert(loc=6, column='eqipments',value='oxygen cylinder')

In [67]:
df

,PassengerId,Survived,Pclass,Food,Name,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,0,"Braund, Mr. Owen Harris",male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
2,3,1,3,0,"Heikkinen, Miss. Laina",female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
3,4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,oxygen cylinder,35.0,1,0,113803,53.1000,C123,S,7
4,5,0,3,0,"Allen, Mr. William Henry",male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,0,"Montvila, Rev. Juozas",male,oxygen cylinder,27.0,0,0,211536,13.0000,NaN,S,7
887,888,1,1,0,"Graham, Miss. Margaret Edith",female,oxygen cylinder,19.0,0,0,112053,30.0000,B42,S,7
888,889,0,3,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,oxygen cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,7
889,890,1,1,0,"Behr, Mr. Karl Howell",male,oxygen cylinder,26.0,0,0,111369,30.0000,C148,C,7
890,891,0,3,0,"Dooley, Mr. Patrick",male,oxygen cylinder,32.0,0,0,370376,7.7500,NaN,Q,7

In [68]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Food', 'Name', 'Sex', 'eqipments',
       'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked',
       'new_col'],
      dtype='object')

In [69]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [70]:
a = df['Name'][0:9]

In [71]:
a

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
Name: Name, dtype: object

In [72]:
type(a)

pandas.core.series.Series

In [73]:
l = ['qasim','2004','a4','9000','223','10','22','October','21']

In [74]:
pd.Series(a, index=l)

qasim      NaN
2004       NaN
a4         NaN
9000       NaN
223        NaN
10         NaN
22         NaN
October    NaN
21         NaN
Name: Name, dtype: object

In [75]:
pd.Series(list(a), index = l)

qasim                                Braund, Mr. Owen Harris
2004       Cumings, Mrs. John Bradley (Florence Briggs Th...
a4                                    Heikkinen, Miss. Laina
9000            Futrelle, Mrs. Jacques Heath (Lily May Peel)
223                                 Allen, Mr. William Henry
10                                          Moran, Mr. James
22                                   McCarthy, Mr. Timothy J
October                       Palsson, Master. Gosta Leonard
21         Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
dtype: object

In [76]:
m1 = pd.Series([100,200,300,400,500], index=[1,2,3,4,5])

In [77]:
m1

1    100
2    200
3    300
4    400
5    500
dtype: int64

In [78]:
m2 = pd.Series([600,700,800,900,1000], index=[1,2,3,4,5])

In [79]:
m2

1     600
2     700
3     800
4     900
5    1000
dtype: int64

In [80]:
m3 = pd.concat([m1,m2])

In [81]:
m3

1     100
2     200
3     300
4     400
5     500
1     600
2     700
3     800
4     900
5    1000
dtype: int64

In [82]:
m3[1]

1    100
1    600
dtype: int64

In [83]:
m1*m2

1     60000
2    140000
3    240000
4    360000
5    500000
dtype: int64

In [84]:
m1+m2

1     700
2     900
3    1100
4    1300
5    1500
dtype: int64

In [85]:
df.head()

,PassengerId,Survived,Pclass,Food,Name,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,0,"Braund, Mr. Owen Harris",male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
2,3,1,3,0,"Heikkinen, Miss. Laina",female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
3,4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,oxygen cylinder,35.0,1,0,113803,53.1000,C123,S,7
4,5,0,3,0,"Allen, Mr. William Henry",male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7

In [86]:
df.drop("PassengerId", axis=1)

,Survived,Pclass,Food,Name,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,0,3,0,"Braund, Mr. Owen Harris",male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
2,1,3,0,"Heikkinen, Miss. Laina",female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
3,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,oxygen cylinder,35.0,1,0,113803,53.1000,C123,S,7
4,0,3,0,"Allen, Mr. William Henry",male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,"Montvila, Rev. Juozas",male,oxygen cylinder,27.0,0,0,211536,13.0000,NaN,S,7
887,1,1,0,"Graham, Miss. Margaret Edith",female,oxygen cylinder,19.0,0,0,112053,30.0000,B42,S,7
888,0,3,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,oxygen cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,7
889,1,1,0,"Behr, Mr. Karl Howell",male,oxygen cylinder,26.0,0,0,111369,30.0000,C148,C,7
890,0,3,0,"Dooley, Mr. Patrick",male,oxygen cylinder,32.0,0,0,370376,7.7500,NaN,Q,7

In [87]:
df.head()

,PassengerId,Survived,Pclass,Food,Name,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,0,"Braund, Mr. Owen Harris",male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
2,3,1,3,0,"Heikkinen, Miss. Laina",female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
3,4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,oxygen cylinder,35.0,1,0,113803,53.1000,C123,S,7
4,5,0,3,0,"Allen, Mr. William Henry",male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7

In [88]:
df.drop("PassengerId", axis=1, inplace=True)

In [89]:
df.head()

,Survived,Pclass,Food,Name,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,0,3,0,"Braund, Mr. Owen Harris",male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
2,1,3,0,"Heikkinen, Miss. Laina",female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
3,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,oxygen cylinder,35.0,1,0,113803,53.1000,C123,S,7
4,0,3,0,"Allen, Mr. William Henry",male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7

In [90]:
df

,Survived,Pclass,Food,Name,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,0,3,0,"Braund, Mr. Owen Harris",male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
2,1,3,0,"Heikkinen, Miss. Laina",female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
3,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,oxygen cylinder,35.0,1,0,113803,53.1000,C123,S,7
4,0,3,0,"Allen, Mr. William Henry",male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,"Montvila, Rev. Juozas",male,oxygen cylinder,27.0,0,0,211536,13.0000,NaN,S,7
887,1,1,0,"Graham, Miss. Margaret Edith",female,oxygen cylinder,19.0,0,0,112053,30.0000,B42,S,7
888,0,3,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,oxygen cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,7
889,1,1,0,"Behr, Mr. Karl Howell",male,oxygen cylinder,26.0,0,0,111369,30.0000,C148,C,7
890,0,3,0,"Dooley, Mr. Patrick",male,oxygen cylinder,32.0,0,0,370376,7.7500,NaN,Q,7

In [91]:
df.drop(3)

,Survived,Pclass,Food,Name,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,0,3,0,"Braund, Mr. Owen Harris",male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
2,1,3,0,"Heikkinen, Miss. Laina",female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
4,0,3,0,"Allen, Mr. William Henry",male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7
5,0,3,0,"Moran, Mr. James",male,oxygen cylinder,NaN,0,0,330877,8.4583,NaN,Q,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,"Montvila, Rev. Juozas",male,oxygen cylinder,27.0,0,0,211536,13.0000,NaN,S,7
887,1,1,0,"Graham, Miss. Margaret Edith",female,oxygen cylinder,19.0,0,0,112053,30.0000,B42,S,7
888,0,3,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,oxygen cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,7
889,1,1,0,"Behr, Mr. Karl Howell",male,oxygen cylinder,26.0,0,0,111369,30.0000,C148,C,7
890,0,3,0,"Dooley, Mr. Patrick",male,oxygen cylinder,32.0,0,0,370376,7.7500,NaN,Q,7

In [92]:
df.head()

,Survived,Pclass,Food,Name,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,0,3,0,"Braund, Mr. Owen Harris",male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
2,1,3,0,"Heikkinen, Miss. Laina",female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
3,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,oxygen cylinder,35.0,1,0,113803,53.1000,C123,S,7
4,0,3,0,"Allen, Mr. William Henry",male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7

In [93]:
df.drop(3, inplace=True)

In [94]:
df

,Survived,Pclass,Food,Name,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,0,3,0,"Braund, Mr. Owen Harris",male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
2,1,3,0,"Heikkinen, Miss. Laina",female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
4,0,3,0,"Allen, Mr. William Henry",male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7
5,0,3,0,"Moran, Mr. James",male,oxygen cylinder,NaN,0,0,330877,8.4583,NaN,Q,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,"Montvila, Rev. Juozas",male,oxygen cylinder,27.0,0,0,211536,13.0000,NaN,S,7
887,1,1,0,"Graham, Miss. Margaret Edith",female,oxygen cylinder,19.0,0,0,112053,30.0000,B42,S,7
888,0,3,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,oxygen cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,7
889,1,1,0,"Behr, Mr. Karl Howell",male,oxygen cylinder,26.0,0,0,111369,30.0000,C148,C,7
890,0,3,0,"Dooley, Mr. Patrick",male,oxygen cylinder,32.0,0,0,370376,7.7500,NaN,Q,7

In [95]:
df.head()

,Survived,Pclass,Food,Name,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,0,3,0,"Braund, Mr. Owen Harris",male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
2,1,3,0,"Heikkinen, Miss. Laina",female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
4,0,3,0,"Allen, Mr. William Henry",male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7
5,0,3,0,"Moran, Mr. James",male,oxygen cylinder,NaN,0,0,330877,8.4583,NaN,Q,7

In [96]:
df.set_index("Name")

,Survived,Pclass,Food,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
Name,,,,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,0,male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,0,female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
"Heikkinen, Miss. Laina",1,3,0,female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
"Allen, Mr. William Henry",0,3,0,male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7
"Moran, Mr. James",0,3,0,male,oxygen cylinder,NaN,0,0,330877,8.4583,NaN,Q,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,0,male,oxygen cylinder,27.0,0,0,211536,13.0000,NaN,S,7
"Graham, Miss. Margaret Edith",1,1,0,female,oxygen cylinder,19.0,0,0,112053,30.0000,B42,S,7
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,0,female,oxygen cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,7
"Behr, Mr. Karl Howell",1,1,0,male,oxygen cylinder,26.0,0,0,111369,30.0000,C148,C,7
"Dooley, Mr. Patrick",0,3,0,male,oxygen cylinder,32.0,0,0,370376,7.7500,NaN,Q,7

In [97]:
df.head()

,Survived,Pclass,Food,Name,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,0,3,0,"Braund, Mr. Owen Harris",male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
2,1,3,0,"Heikkinen, Miss. Laina",female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
4,0,3,0,"Allen, Mr. William Henry",male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7
5,0,3,0,"Moran, Mr. James",male,oxygen cylinder,NaN,0,0,330877,8.4583,NaN,Q,7

In [98]:
df.set_index("Name", inplace=True)

In [99]:
df

,Survived,Pclass,Food,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
Name,,,,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,0,male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,0,female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
"Heikkinen, Miss. Laina",1,3,0,female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
"Allen, Mr. William Henry",0,3,0,male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7
"Moran, Mr. James",0,3,0,male,oxygen cylinder,NaN,0,0,330877,8.4583,NaN,Q,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,0,male,oxygen cylinder,27.0,0,0,211536,13.0000,NaN,S,7
"Graham, Miss. Margaret Edith",1,1,0,female,oxygen cylinder,19.0,0,0,112053,30.0000,B42,S,7
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,0,female,oxygen cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,7
"Behr, Mr. Karl Howell",1,1,0,male,oxygen cylinder,26.0,0,0,111369,30.0000,C148,C,7
"Dooley, Mr. Patrick",0,3,0,male,oxygen cylinder,32.0,0,0,370376,7.7500,NaN,Q,7

In [100]:
df.reset_index()

,Name,Survived,Pclass,Food,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,"Braund, Mr. Owen Harris",0,3,0,male,oxygen cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,7
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,0,female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
2,"Heikkinen, Miss. Laina",1,3,0,female,oxygen cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7
3,"Allen, Mr. William Henry",0,3,0,male,oxygen cylinder,35.0,0,0,373450,8.0500,NaN,S,7
4,"Moran, Mr. James",0,3,0,male,oxygen cylinder,NaN,0,0,330877,8.4583,NaN,Q,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,"Montvila, Rev. Juozas",0,2,0,male,oxygen cylinder,27.0,0,0,211536,13.0000,NaN,S,7
886,"Graham, Miss. Margaret Edith",1,1,0,female,oxygen cylinder,19.0,0,0,112053,30.0000,B42,S,7
887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,0,female,oxygen cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,7
888,"Behr, Mr. Karl Howell",1,1,0,male,oxygen cylinder,26.0,0,0,111369,30.0000,C148,C,7
889,"Dooley, Mr. Patrick",0,3,0,male,oxygen cylinder,32.0,0,0,370376,7.7500,NaN,Q,7

# Making a dataframe from the dictionary

In [101]:
d = {
     "key1":[1,2,3,4,5],
     "key2":[6,7,8,9,10],
     "key3":[11,12,13,14,15]
}

In [102]:
print(d)

{'key1': [1, 2, 3, 4, 5], 'key2': [6, 7, 8, 9, 10], 'key3': [11, 12, 13, 14, 15]}

In [103]:
pd.DataFrame(d)

   key1  key2  key3
0     1     6    11
1     2     7    12
2     3     8    13
3     4     9    14
4     5    10    15

In [104]:
df.dropna()

,Survived,Pclass,Food,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
Name,,,,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,0,female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
"McCarthy, Mr. Timothy J",0,1,0,male,oxygen cylinder,54.0,0,0,17463,51.8625,E46,S,7
"Sandstrom, Miss. Marguerite Rut",1,3,0,female,oxygen cylinder,4.0,1,1,PP 9549,16.7000,G6,S,7
"Bonnell, Miss. Elizabeth",1,1,0,female,oxygen cylinder,58.0,0,0,113783,26.5500,C103,S,7
"Beesley, Mr. Lawrence",1,2,0,male,oxygen cylinder,34.0,0,0,248698,13.0000,D56,S,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,1,0,female,oxygen cylinder,47.0,1,1,11751,52.5542,D35,S,7
"Carlsson, Mr. Frans Olof",0,1,0,male,oxygen cylinder,33.0,0,0,695,5.0000,B51 B53 B55,S,7
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,1,0,female,oxygen cylinder,56.0,0,1,11767,83.1583,C50,C,7
"Graham, Miss. Margaret Edith",1,1,0,female,oxygen cylinder,19.0,0,0,112053,30.0000,B42,S,7
"Behr, Mr. Karl Howell",1,1,0,male,oxygen cylinder,26.0,0,0,111369,30.0000,C148,C,7

In [105]:
df.dropna(inplace=True)

In [106]:
df

,Survived,Pclass,Food,Sex,eqipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
Name,,,,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,0,female,oxygen cylinder,38.0,1,0,PC 17599,71.2833,C85,C,7
"McCarthy, Mr. Timothy J",0,1,0,male,oxygen cylinder,54.0,0,0,17463,51.8625,E46,S,7
"Sandstrom, Miss. Marguerite Rut",1,3,0,female,oxygen cylinder,4.0,1,1,PP 9549,16.7000,G6,S,7
"Bonnell, Miss. Elizabeth",1,1,0,female,oxygen cylinder,58.0,0,0,113783,26.5500,C103,S,7
"Beesley, Mr. Lawrence",1,2,0,male,oxygen cylinder,34.0,0,0,248698,13.0000,D56,S,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,1,0,female,oxygen cylinder,47.0,1,1,11751,52.5542,D35,S,7
"Carlsson, Mr. Frans Olof",0,1,0,male,oxygen cylinder,33.0,0,0,695,5.0000,B51 B53 B55,S,7
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,1,0,female,oxygen cylinder,56.0,0,1,11767,83.1583,C50,C,7
"Graham, Miss. Margaret Edith",1,1,0,female,oxygen cylinder,19.0,0,0,112053,30.0000,B42,S,7
"Behr, Mr. Karl Howell",1,1,0,male,oxygen cylinder,26.0,0,0,111369,30.0000,C148,C,7